apiVersion: v1
kind: Service
metadata:
  name: gitlab 
spec:
  ports:
    - name: http
      port: 80 
      protocol: TCP
      targetPort: 10080 
    - name: ssh
      port: 22 
      protocol: TCP
      targetPort: 10022 
