apiVersion: v1
kind: Endpoints
metadata:
  name: gitlab 
  namespace: default
subsets:
  - addresses:
    - ip: 10.1.0.32
    ports:
      - name: http
        port: 10080 
      - name: ssh
        port: 10022 
